FROM golang:1.14.4-alpine3.12 AS builder

# install build environment
RUN echo "https://mirror.tuna.tsinghua.edu.cn/alpine/v3.12/main" > /etc/apk/repositories
RUN apk add --no-cache build-base git vim


